### ISSUE TITLE
project settings crash

### ISSUE THREAD

**Issue by cs42** [Surgo/redmine_reposearch#15]
After activating reposarch for a project, I can't open the project settings anylonger, as redmine crashes with following message:

```
Rendering template within layouts/base
Rendering projects/settings

ActionView::TemplateError (Missing host to link to! Please provide :host parameter or set default_url_options[:host
]) on line #19 of app/views/projects/settings/_repository.html.erb:
16: <% button_disabled = true %>
17: <% if @repository %>
18: <%   button_disabled = ! @repository.class.scm_available %>
19: <%=    repository_field_tags(f, @repository)%>
20: <% end %>
21: </div>
22:

    (eval):21:in `root_url'
    app/helpers/repositories_helper.rb:161:in `subversion_field_tags'
    app/helpers/repositories_helper.rb:125:in `send'
    app/helpers/repositories_helper.rb:125:in `repository_field_tags_without_checkout'
    app/views/projects/settings/_repository.html.erb:19
    app/views/projects/settings/_repository.html.erb:1
    app/views/common/_tabs.html.erb:24
    app/views/common/_tabs.html.erb:23:in `each'
    app/views/common/_tabs.html.erb:23
    app/helpers/application_helper.rb:222:in `render_tabs'
    app/views/projects/settings.html.erb:3
```

I had a look at the code of the reposearch plugin, but have no clue, where that is coming from...

**Comment by cs42** [comment]
BTW: I'm running Redmine 1.3.1.stable

**Comment by cforce** [comment]
same here!

**Comment by cforce** [comment]
Please fix the bugs. there are already two issues and 5 users reporrting it

https://github.com/Surgo/redmine_reposearch/issues/15
https://github.com/Surgo/redmine_reposearch/issues/11

**Comment by Surgo** [comment]
@cs42 @cforce plese please check new version.

**Comment by Surgo** [comment]
http://www.redmine.org/issues/4725
